### PR TITLE
fix: movies only shown to their creators

### LINKED ISSUE #17: i haven't added this move i should not see it
image

### PR DESCRIPTION
**Pull request by ninadarbaidze**
closes #17

### CODE REVIEW

File: components/Movies/ListOfMovies/useListOfMovies.ts [hunk 1]
```diff
@@ -26,8 +26,10 @@ export const useListOfMovies = () => {
   useEffect(() => {
     const getData = async () => {
       let token = session ? session.accessToken : ctx.token;
+      const userId = session ? session.userId : ctx.userId;
+      console.log(userId);
```
Comment (GigaGiorgadze) [inline components/Movies/ListOfMovies/useListOfMovies.ts]: remove console log

**Review by GigaGiorgadze — APPROVED** [review]

**Review by GigaGiorgadze — CHANGES_REQUESTED** [review]
ops missclick

**Review by GigaGiorgadze — APPROVED** [review]
